
const SOCKET_MESSAGE = {
    JOIN_ROOM: 'JOIN_ROOM',
    USER_CONNECTED: 'USER_CONNECTED',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    SEND_MESSAGE: 'SEND_MESSAGE',
    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
    EXIT_ROOM: 'EXIT_ROOM'
}

module.exports = {
    SOCKET_MESSAGE
}