
const SOCKET_MESSAGE = {
    JOIN_ROOM: 'JOIN_ROOM',
    JOINED_ROOM: 'JOINED_ROOM',
    USER_CONNECTED: 'USER_CONNECTED',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    SEND_MESSAGE: 'SEND_MESSAGE',
    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
    RECONNECTED: 'RECONNECTED',
    USER_RECONNECTED: 'USER_RECONNECTED',
    EXIT_ROOM: 'EXIT_ROOM'
}

module.exports = {
    SOCKET_MESSAGE
}